services:
  apache:
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  pma:
    restart: always
    environment:
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  database:
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
