services:
  apache:
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=development
      - DB_USER=root
      - DB_PASSWORD=123456789
  pma:
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
  database:
    volumes:
      - dev_db:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=development
volumes:
  dev_db: {}
