services:
  apache:
    build: ./dockerfiles/web
    volumes:
      - ./src:/var/www/html
    ports:
      - 9999:80
    environment:
      - DB_HOST=database
      - DB_PORT=3306
  pma:
    image: phpmyadmin:5.2-apache
    ports:
      - 7777:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
  database:
    image: mysql:8-debian
