services:
  apache:
    build: ./dockerfiles/web
    restart: always
    volumes:
      - ./src:/var/www/html
    ports: 
      - 9999:80
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  pma:
    image: phpmyadmin:5.2-apache
    restart: always
    ports:
      - 7777:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  database:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
